### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by retorquere** [crystal-lang/install-crystal#44] opened 2024-07-09 20:58 UTC
Installation fails with

```
Run crystal-lang/install-crystal@v1
Installing package dependencies
Looking for crystal-lang/crystal-lang release (latest)
sudo -n apt-get install -qy --no-install-recommends --no-upgrade -- libevent-dev libgmp-dev libpcre3-dev libssl-dev libxml2-dev libyaml-dev libpcre2-dev
Getting Crystal release (1.13.0)
Found Crystal release https://github.com/crystal-lang/crystal/releases/tag/1.13.0
Error: TypeError: Cannot read properties of undefined (reading 'url')
```

**Comment by oprypin** [comment] 2024-07-09 21:22
This is very likely a temporary issue as the release is being uploaded. Can you try again and check if it works?

**Comment by retorquere** [comment] 2024-07-09 21:37
It doesn't. But replacing it with

```
run: curl -fsSL https://crystal-lang.org/install.sh | sudo bash
```

does the job too

**Comment by Blacksmoke16** [comment] 2024-07-09 21:40
Duplicate of https://github.com/crystal-lang/install-crystal/issues/12

**Closed by Blacksmoke16** 2024-07-09 21:40 UTC
